AWSTemplateFormatVersion: '2010-09-09'
Description: Build Iot Core and Policy

Resources:
  Thing:
    Type: AWS::IoT::Thing
    Properties:
      ThingName: lksiot

  Policy:
    Type: AWS::IoT::Policy
    Properties:
      PolicyName: lksiotpolicies
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - iot:Connect
            Resource:
              - '*'
          - Effect: Allow
            Action:
              - iot:Publish
            Resource:
              - '*'       
          - Effect: Allow
            Action:
              - iot:Receive
            Resource:
              - '*'       
          - Effect: Allow
            Action:
              - iot:Subscribe
            Resource:
              - '*'